# 检测代码能否正常编译

name: Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: download runtime dependency
        run: pip install gitpython
      - name: build artifact
        run: python main.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: "IDFv*.zip"